[package]
name = "marklessman-gui"
edition = "2024"
version.workspace = true

[dependencies]
dirs = "6"
eframe = "0.36"
egui_extras = { version = "0.36", features = ["all_loaders"] }
fast-down-api = { git = "https://github.com/fast-down/core.git", rev = "b93ab2c0eb11ffe7acbced5dd200afd7fe45b623" }
image.workspace = true
marklessman-core = { version = "0.1", path = "../marklessman-core" }
rfd = "0.17"
tokio = { version = "1", features = ["rt", "rt-multi-thread", "macros", "sync", "time"] }
tokio-util = "0.7"
url = "2"
